let dict = {
  ا: "alef.svg",
  ع: "ain.svg",
  ف: "fa.svg",
  0: "0.svg",
  3: "3.svg",
  ب: "ba.svg",
  ض: "dhad.svg",
  ارسل: "envoyer.svg",
  غ: "ghain.svg",
  ه: "ha.svg",
  احبك: "i love you.svg",
  ج: "jeem.svg",
  ك: "kaaf.svg",
  لا: "lla-negation.svg",
  م: "meem.svg",
  ر: "ra.svg",
  ص: "saad.svg",
  س: "seen.svg",
  ت: "ta.svg",
  ث: "thaa.svg",
  نصر: "victoire.svg",
  ي: "ya.svg",
  ل: "laam.svg",


  "ما": "fa.svg",
  "a": "001-letter a.svg",
  "b":"012-letter b.svg",
  "الوثيقه":"012-letter b.svg",
  "c":"023-letter c.svg",
  "d":"034-letter d.svg",
  "e":"045-letter e.svg",
  "f":"047-letter f.svg",
  "g":"048-letter g.svg",
  "h":"049-letter h.svg",
  "i":"050-letter i.svg",
  "j":"002-letter j.svg",
  "k":"003-letter k.svg",
  "l":"004-letter l.svg",
  "m":"005-letter m.svg",
  "n":"006-letter n.svg",
  "o":"007-letter o.svg",
  "p":"008-letter p.svg",
  "q":"009-letter q.svg",
  "r":"010-letter r.svg",
  "s":"011-Letter s.svg",
  "t":"013-letter t.svg",
  "u":"014-letter u.svg",
  "v":"015-letter v.svg",
  "اللقاء":"015-letter v.svg",
  "w":"016-letter w.svg",
  "x":"017-letter x.svg",
  "نوع":"017-letter x.svg",
  "y":"018-letter y.svg",
  "غدا":"018-letter y.svg",
  "z":"019-letter z.svg",
  "like":"030-like.svg",
  "wow":"020-wow.svg",
  "bathroom":"022-bathroom.svg",
  "farewell":"025-Farewell.svg",
  "come":"026-come.svg",
  "ارجع":"026-come.svg",
  "cv":"027-what are you doing.svg",
  "equality":"028-equality.svg",
  "far":"029-far.svg",
  "ok":"031-ok.svg",
  "good":"032-good.svg",
  "stop":"033-stop.svg",
  "hello":"035-hello.svg",
  "السلام":"035-hello.svg",
  "i love you":"037-i love you.svg",
  "later":"039-later.svg",
  "lol":"040-lol.svg",
  "no":"041-No.svg",
  "perfect":"042-perfect.svg",
  "question":"043-question.svg",
};

export default dict;
