let characters = [
    [
        ["1", "3.svg"],
        ["2", "0.svg"],
        ["3", "3.svg"],
        ["4", "0.svg"],
        ["5", "3.svg"],
        ["6", "0.svg"],
        ["7", "3.svg"],
        ["8", "0.svg"],
        ["9", "3.svg"],
        ["0", "0.svg"],
    ],
    [
        ["a", "001-letter a.svg"],
        ["z","019-letter z.svg"],
        ["e","045-letter e.svg"],
        ["r","010-letter r.svg"],
        ["t","013-letter t.svg"],
        ["y","018-letter y.svg"],
        ["u","014-letter u.svg"],
        ["i","050-letter i.svg"],
        ["o","007-letter o.svg"],
        ["p","008-letter p.svg"],
    ],
    [
        ["q","009-letter q.svg"],
        ["s","011-Letter s.svg"],
        ["d","034-letter d.svg"],
        ["f","047-letter f.svg"],
        ["g","048-letter g.svg"],
        ["h","049-letter h.svg"],
        ["j","002-letter j.svg"],
        ["k","003-letter k.svg"],
        ["l","004-letter l.svg"],
        ["m","005-letter m.svg"],
    ],
    [
        ["","space.png"],
        ["","space.png"],
        ["w","016-letter w.svg"],
        ["x","017-letter x.svg"],
        ["c","023-letter c.svg"],
        ["v","015-letter v.svg"],
        ["b","012-letter b.svg"],
        ["n","006-letter n.svg"],
        [" ","space.png"],
        [" ","space.png"],
    ],
];
  
export default characters;
  